### ISSUE TITLE
Script attached to "sub_canvas" in scene "lucky.fire" is missing or invalid.

### ISSUE THREAD

**Issue by CodeLifexHub** [zx6733090/SixClear#1]
Node path: "Canvas/rank/sub_canvas"
Asset url: "db://assets/lucky.fire"

Node path: "Canvas/home/sub_canvas"
Asset url: "db://assets/lucky.fire"

Node path: "Canvas/over/sub_canvas"
Asset url: "db://assets/lucky.fire"

**Comment by zx6733090** [comment]
What version do you use？  Recommended to use cocos creator v2.0.8 or  lower version.
